config {
    type: "table",
    schema: "m_blup",
    description: "Esta tabla contiene informacion sobre las farmacias. / This table contains information about the drugstores.",
    columns: {
    "id_drugstore": "Número de fila de la farmacia / Drugstore row number",
    "key_drugstore": "Clave de negocio de la farmacia / Drugstore business key",
    "drugstore_name": "Nombre de la farmacia / Drugstore name",
    "drugstore_address": "Dirección de la farmacia / Drugstore address",
    "drugstore_type_association": "Tipo de asociación de la farmacia / Drugstore association type",
    "company_name": "Nombre de la compañía / Company name",
    "city_name": "Nombre de la ciudad / City name"
},
    assertions: {
     uniqueKey: ["id_drugstore"]
  },
    tags: ["dimension"]
}

select 
ROW_NUMBER() OVER() AS id_drugstore,
d.id as key_drugstore, 
d.name as drugstore_name, 
d.address as drugstore_address, 
d.type_association as drugstore_type_association,
c.name as company_name,
ci.name as city_name
from `datamartblup.db_blup.drugstores` d 
left join `datamartblup.db_blup.companies` c on d.company_id = c.id
left join `datamartblup.db_blup.cities` ci on d.city_id = ci.id